baseURL = "http://sofiejuhl.dk/KEA/3semester/Hugo_designsystem"
languageCode = "da-dk"
title = "My New Hugo Site"
theme = "systematik"

[[menu.main]]
    name = "Home"
    title = "home section"
    weight = 1
    identifier = "home"
    url = "/"

[[menu.main]]
    name = "Dokumentation"
    title = "dokumentation section"
    weight = 2
    identifier = "dokumentation"
    url = "/dokumentation"

[[menu.main]]
    name = "Kontakt"
    title = "Kontakt"
    weight = 3
    identifier = "om"
    url = "/om"



